### ISSUE TITLE
部分怪物贴图问题

### ISSUE THREAD

**Issue by beifeng233** [ANTIHERO331/enhanced-mite#1]
部分怪物（石头人和一些红眼怪物）发光部分会出现透明的情况，建议修复一下，应该是没有把眼睛贴到本体材质的问题

**Comment by ANTIHERO331** [comment]
此问题已被确认为非技术性问题（即纯纯材质bug），所以一次修复没法一劳永逸。这里需要一个有此问题的所有实体的名单，我会在v0.6中修复
