### ISSUE TITLE
两个熔炉的细节问题

### ISSUE THREAD

**Issue by beifeng233** [ANTIHERO331/enhanced-mite#2]
1.沙石炉--沙石在高版本变为了砂岩，所以“沙石炉”译名应改为“砂岩熔炉”
2.硬化黏土熔炉--硬化黏土在高版本变为了陶瓦，所以硬化黏土熔炉合成方式应改为8个陶瓦而不是4个砖块；并且译名改为“陶瓦熔炉”
（陶瓦可改为在黏土熔炉烧制黏土块获得）

**Comment by ANTIHERO331** [comment]
问题修复已在v0.5.1中生效
